### ISSUE TITLE
Discussion: 
                SSOSettingsFileReader error
            

### ISSUE THREAD

**Issue by tfabraham** [BTDF/CodePlexDiscussions#82]
<b>josephfusco[4/14/2010 3:33:27 AM]</b>
tfabraham wrote:
This is fixed in 5.0.16, available now on the Downloads page. Thanks for reporting this! Tom

I am using Latest version Beta for BTS 2013 but this error still persist 

System.IO.FileNotFoundException: Could not load file or assembly 'SSOSettingsFileReader ,Version=1.0.0.0, Culture=neutral, PublicKeyToken=b9585ffc9d454e4a' or one of its dependencies. The system cannot find the file specified at DeploymentFramework.BuildTasks.UpdateSSOConfigItem.Execute()

Its working on development box but not on test or stage machines.

**Comment by tfabraham** [comment]
<b>tfabraham</b>
<b>abhishek1301</b>
<b>tfabraham</b>
<b>NealWalters</b>
<b>tfabraham</b>
<b>josephfusco</b>
<b>tfabraham</b>
<b>josephfusco</b>
<b>tfabraham</b>
<b>tfabraham</b>
<b>josephfusco</b>
<b>tfabraham</b>
<b>josephfusco</b>
<b>tfabraham</b>
SSOSettingsFileReader.dll is always deployed to the GAC automatically. Do you have anything named AdditionalAssemblies in your .btdfproj? Please search for Deploying additional assemblies to GAC... in the log after a deployment and capture the log output
 for review. 

Thanks, 
Tom

**Comment by tfabraham** [comment]
<b>abhishek1301</b>
I am only deploying schemas, maps, orchestration, and pipelines. I have Include SSO true. An application is being created in SSO when I see it from SSOSetting Editor. I am not recognising that how SSOSettingEditor is working though it also uses SSOSettingFileReader.dll.
 I tried to run SSOSettingFileImport alone. It is also creating an application in SSO. But when I try to run MSI on other boxes it fails in UpdateSSOConfigItem step saying file not found error.

**Comment by tfabraham** [comment]
<b>tfabraham</b>
Please capture the log output from the DeployResults.txt on one of the servers. Search for Deploying additional assemblies to GAC.


Thanks, 
Tom

**Comment by tfabraham** [comment]
<b>abhishek1301</b>
<b>abhishek1301</b>
Build started 2013-06-13 17:46:00.

Project "D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj" (Deploy target(s)):


Target Deploy:
```
Target SetModeDeploy:
    DEPLOYING APPLICATION TO BIZTALK...
Target ServerDeploy:
    Target SetWinVer:
        Running on Windows V61
        Detected IIS 7
        Detected 64-bit OS
    Target GetSoftwarePaths:
        Using .NET Framework Install Path 'C:\Windows\Microsoft.NET\Framework\v4.0.30319'.
        Using BizTalk Install Path 'C:\Program Files (x86)\Microsoft BizTalk Server 2013\'.
        Using Deployment Framework Install Path 'D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\'.
        Using Deployment Framework Tools Path 'D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Framework\DeployTools'.
    Target ExportSettings:
        "D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Framework\DeployTools\EnvironmentSettingsExporter.exe" "D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\EnvironmentSettings\SettingsFileGenerator.xml" "D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\EnvironmentSettings"
        Environment Settings Spreadsheet to XML Exporter 1.6.1
        [http://EnvSettingsManager.codeplex.com]
        Copyright (C) 2007-11 Thomas F. Abraham.  All Rights Reserved.

        Importing from SettingsFileGenerator.xml...

        Output format is XmlPreprocess (multi-file).

        Exporting to Exported_LocalSettings.xml...
        Exporting to Exported_DevSettings.xml...
        Exporting to Exported_TestSettings.xml...
        Exporting to Exported_ProdSettings.xml...

        Finished.
    Target InitSettingsFilePath:
        SetRegistryValue: Attempting to create/update value 'D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\EnvironmentSettings\Exported_TestSettings.xml' in registry value 'LastDeploySettingsFilePath' at key 'HKEY_LOCAL_MACHINE\SOFTWARE\Vattenfall AB\XXXXXXXXXXXXXXX'...
        SetRegistryValue: Successfully created/updated value.
        Using settings file D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\EnvironmentSettings\Exported_TestSettings.xml
    Target SetPropertiesFromEnvironmentSettings:
        Setting properties from environment settings file (D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\EnvironmentSettings\Exported_TestSettings.xml)
        Setting property to value 'MYDOMAIN\User'.
        Setting property to value 'MYDOMAIN\Admin'.
    Target InitializeAppName:
        BizTalk Application Name is XXXXXXXXXXXXXXX
    Target PreprocessBindings:
        Clearing file attributes for '..\Bindings\XXXXXXXXXXXXXXX.xml'.
        "D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Framework\DeployTools\xmlpreprocess.exe" /f /v /c /noDirectives /i:"D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\XXXXXXXXXXXXXXX.PortBindingsMaster.xml" /o:"D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\..\Bindings\XXXXXXXXXXXXXXX.Bindings.xml" /d:CurDir="D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0" /s:"D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\EnvironmentSettings\Exported_TestSettings.xml"
        XmlPreprocess v2.0.13.0
        Copyright (c) 2004-2010 Loren M Halvorson
        XML File Preprocessor

        Settings XML file: "D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\EnvironmentSettings\Exported_TestSettings.xml"
        Preprocessing "D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\XXXXXXXXXXXXXXX.PortBindingsMaster.xml" to "D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\..\Bindings\XXXXXXXXXXXXXXX.Bindings.xml"...
        XXXXXXXXXXXXXXX.Bindings.xml : Set the value 'XXXXXXXXXXXXXXX' of 6 node(s) matching XPath '//ApplicationName'.
        "D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Framework\DeployTools\ElementTunnel.exe" /i:"D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\..\Bindings\XXXXXXXXXXXXXXX.Bindings.xml" /o:"D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\..\Bindings\XXXXXXXXXXXXXXX.Bindings.xml" /x:"D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Framework\DeployTools\adapterXPaths.txt" /encode
        Nested XML Encoder/Decoder v5.1.100.0
        Copyright (C) 2005-2013 Scott Colestock, Tim Rayburn, Thomas F. Abraham

        XML encodes/decodes content of element(s) by XPath. Applies escaping rules such
        as &gt; for '<'. Namespace decls, PIs, etc. of nested XML are not preserved.

        XPaths                        : 15
        Transformed Nodes             : 0
        Empty Nodes (skipped)         : 7
        No Transform Req'd (skipped)  : 18
        Total Matched Nodes           : 25

        Complete - output file has been saved.
    Target CustomSSODeploy:
        "D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Framework\DeployTools\SSOSettingsFileImport.exe" "XXXXXXXXXXXXXXX" /deleteApp
        Affiliate application 'XXXXXXXXXXXXXXX' deleted.
        "D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Framework\DeployTools\SSOSettingsFileImport.exe" "XXXXXXXXXXXXXXX" /settingsFile:"D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\EnvironmentSettings\Exported_TestSettings.xml" /userGroupName:"MYDOMAIN\USer" /adminGroupName:"MYDOMAIN\Admin"
        Affiliate application 'XXXXXXXXXXXXXXX' was created.
        Settings file was associated with application 'XXXXXXXXXXXXXXX' in SSO.
        D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: The "UpdateSSOConfigItem" task failed unexpectedly.
        D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'SSOSettingsFileReader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b9585ffc9d454e4a' or one of its dependencies. The system cannot find the file specified.
        D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: File name: 'SSOSettingsFileReader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b9585ffc9d454e4a'
        D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018:    at DeploymentFramework.BuildTasks.UpdateSSOConfigItem.Execute()
        D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
        D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()
        D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: 
        D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: WRN: Assembly binding logging is turned OFF.
        D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
        D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: Note: There is some performance penalty associated with assembly bind failure logging.
        D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
        D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: 
    Done building target "CustomSSODeploy" in project "Deployment.btdfproj" -- FAILED.
Done building target "ServerDeploy" in project "Deployment.btdfproj" -- FAILED.
```
Done building target "Deploy" in project "Deployment.btdfproj" -- FAILED.


Done building project "Deployment.btdfproj" -- FAILED. 

Build FAILED. 

D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: The "UpdateSSOConfigItem" task failed unexpectedly.

D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'SSOSettingsFileReader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b9585ffc9d454e4a' or one of its
 dependencies. The system cannot find the file specified. 
D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: File name: 'SSOSettingsFileReader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b9585ffc9d454e4a'

D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: at DeploymentFramework.BuildTasks.UpdateSSOConfigItem.Execute()

D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()

D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()

D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018:

D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: WRN: Assembly binding logging is turned OFF.

D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: Note: There is some performance penalty associated with assembly bind failure logging.

D:\BizTalkApps\XXXXXXXXXXXXXXX\1.0\Deployment\Deployment.btdfproj(179,5): error MSB4018: To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!Enab

**Comment by tfabraham** [comment]
<b>abhishek1301</b>
I also tried this link alos but no luck.. 

http://snefs.blogspot.nl/2013/05/biztalk-deployment-framework-btdf-51.html

**Comment by tfabraham** [comment]
<b>tfabraham</b>
You have added a custom target CustomSSODeploy that runs before the assemblies have even been deployed. You should schedule your custom target to run after DeploySharedAssemblies, and probably after DeploySSO.


Tom

**Comment by tfabraham** [comment]
<b>abhishek1301</b>
It worked. MSI installation doesn't work. I ran the .bat file as admin it worked.

Thanks for your quick response. Will come back with new issues if occurs :) :) It may multiple BAM activity deployment (in different definition files)

**Comment by tfabraham** [comment]
<b>abhishek1301</b>
Hi Tom, 
I found the real issue now but not the solution. I have BizTalk clustered environment(2 instances). When I run the msi on instance1 it works fine. But when I run the msi from instance2 it gives the above error (SSOFileReader.dll not found).

Issue is with GACing of SSOSettingFileReader. I am not able able to understand why it is not gaced in 2nd isntance.

What could be the possible reason. Please suggest.

**Comment by tfabraham** [comment]
<b>tfabraham</b>
As I mentioned above, you have implemented your own custom SSO deployment (CustomSSODeploy target) and that is the source of the problem. It appears that the custom target is a copy of the default DeploySSO target except with a property that overrides
 the SSO app name. 

If you change the Name of the target CustomDeployTarget to CustomSSO, it will execute your custom SSO processing after the assembly has been deployed to the GAC.


Tom
